### PR TITLE
Fix code style against PEP8

### PR DESCRIPTION
**Pull request by fnattino**
(forked from #109, merge that first)

Fixes for making the code PEP8 compliant.

### CODE REVIEW

**Comment by fnattino** [comment]
Tests are now activated and running every time a commit modifies a code-related file (for now, only on ubuntu and with Python==3.8). There are still few failing tests related to PEP8 violations, in particular related to:
* the usage of `I` and `l` as variable names;
* bare except statements.
After these are solved, this PR can be merged - fixing the other failing tests should be addressed in a new PR.

**Comment by fnattino** [comment]
Hi @dicaearchus, the conflicts with the master branch have been fixed. These are the last few code style   fixes required for the code to be compliant to PEP8 (`l` and `I` cannot be used as variable names, and few bare excepts): 
```
dhdt/dhdt/processing/matching_tools_frequency_subpixel.py:198: E741 ambiguous variable name 'l'
dhdt/dhdt/processing/matching_tools_frequency_subpixel.py:387: E722 do not use bare 'except'
dhdt/dhdt/processing/matching_tools_frequency_subpixel.py:674: E722 do not use bare 'except'
dhdt/dhdt/processing/matching_tools_spatial_metrics.py:626: E722 do not use bare 'except'
dhdt/dhdt/processing/matching_tools_spatial_metrics.py:631: E722 do not use bare 'except'
dhdt/dhdt/processing/matching_tools_spatial_subpixel.py:65: E722 do not use bare 'except'
dhdt/dhdt/processing/photohypsometric_image_refinement.py:145: E722 do not use bare 'except'
dhdt/dhdt/postprocessing/photohypsometric_tools.py:1256: E722 do not use bare 'except'
dhdt/dhdt/generic/mapping_tools.py:513: E722 do not use bare 'except'
dhdt/dhdt/generic/orbit_tools.py:500: E722 do not use bare 'except'
dhdt/dhdt/preprocessing/color_transforms.py:129: E741 ambiguous variable name 'I'
dhdt/dhdt/preprocessing/shadow_transforms.py:207: E741 ambiguous variable name 'I'
dhdt/dhdt/preprocessing/shadow_transforms.py:241: E741 ambiguous variable name 'I'
dhdt/dhdt/preprocessing/shadow_transforms.py:480: E741 ambiguous variable name 'I'
dhdt/dhdt/preprocessing/shadow_transforms.py:758: E741 ambiguous variable name 'I'
dhdt/dhdt/preprocessing/shadow_transforms.py:793: E741 ambiguous variable name 'I'
dhdt/dhdt/preprocessing/shadow_transforms.py:904: E741 ambiguous variable name 'I'
dhdt/dhdt/preprocessing/shadow_transforms.py:935: E741 ambiguous variable name 'I'
```

**Comment by dicaearchus** [comment]
Hey Francesco,

I have now resolved these pep8 inconsistencies, hence if you pull these changes, the branch can be merged, right?

Best, Bas

From: Francesco Nattino ***@***.***>
Date: Sunday, 19 November 2023 at 21:37
To: GO-Eratosthenes/dhdt ***@***.***>
Cc: Altena, B. (Bas) ***@***.***>, Mention ***@***.***>
Subject: Re: [GO-Eratosthenes/dhdt] Fix code style against PEP8 (PR #110)
CAUTION: This email originated from outside of Utrecht University. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi @dicaearchus<https://github.com/dicaearchus>, the conflicts with the master branch have been fixed. These are the last few code style fixes required for the code to be compliant to PEP8 (l and I cannot be used as variable names, and few bare excepts):

dhdt/dhdt/processing/matching_tools_frequency_subpixel.py:198: E741 ambiguous variable name 'l'

dhdt/dhdt/processing/matching_tools_frequency_subpixel.py:387: E722 do not use bare 'except'

dhdt/dhdt/processing/matching_tools_frequency_subpixel.py:674: E722 do not use bare 'except'

dhdt/dhdt/processing/matching_tools_spatial_metrics.py:626: E722 do not use bare 'except'

dhdt/dhdt/processing/matching_tools_spatial_metrics.py:631: E722 do not use bare 'except'

dhdt/dhdt/processing/matching_tools_spatial_subpixel.py:65: E722 do not use bare 'except'

dhdt/dhdt/processing/photohypsometric_image_refinement.py:145: E722 do not use bare 'except'

dhdt/dhdt/postprocessing/photohypsometric_tools.py:1256: E722 do not use bare 'except'

dhdt/dhdt/generic/mapping_tools.py:513: E722 do not use bare 'except'

dhdt/dhdt/generic/orbit_tools.py:500: E722 do not use bare 'except'

dhdt/dhdt/preprocessing/color_transforms.py:129: E741 ambiguous variable name 'I'

dhdt/dhdt/preprocessing/shadow_transforms.py:207: E741 ambiguous variable name 'I'

dhdt/dhdt/preprocessing/shadow_transforms.py:241: E741 ambiguous variable name 'I'

dhdt/dhdt/preprocessing/shadow_transforms.py:480: E741 ambiguous variable name 'I'

dhdt/dhdt/preprocessing/shadow_transforms.py:758: E741 ambiguous variable name 'I'

dhdt/dhdt/preprocessing/shadow_transforms.py:793: E741 ambiguous variable name 'I'

dhdt/dhdt/preprocessing/shadow_transforms.py:904: E741 ambiguous variable name 'I'

dhdt/dhdt/preprocessing/shadow_transforms.py:935: E741 ambiguous variable name 'I'

**Comment by fnattino** [comment]
Hi @dicaearchus, great, perfect! I have pulled in the changes and fixed few other issues with PEP8. So now the test in `test_list.py` passes and we have no more conflicts with the master branch! 🎉 

Also, I have run (once more) `isort` (sorts import statements alphabetically, separating standard library and dependency imports in blocks) and `yapf` (code formatter):
```shell
# run isort 
isort dhdt 
# run yapf
yapf -i --recursive dhdt 
```   
These tools help to keep code format homogeneous. You can install them with `pip install dhdt[dev]` (they are specified as part of the  "dev" extra dependencies in `pyproject.toml`).

There are still quite few tests that are not passing, but maybe fixing these can be addressed in a new PR?

**Pull request merged**
